name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake for PQL
      run: cd pql; cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build PQL
      run: cd pql; cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test PQL
      run: cd ${{github.workspace}}/build; ctest --verbose
